name: dither
description: Various dither algorithms for image.
version: 1.0.0
author: myamolane <myamolane@outlook.com>
homepage: https://github.com/myamolane/dither-dart
publish_to: https://pub.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  image: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
